language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DargLine="-Dbigquery.project=dummy-project"
script: mvn clean verify checkstyle:checkstyle findbugs:findbugs -DargLine="-Dbigquery.project=dummy-project"

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    - flatmap-squad@spotify.com
