language: java
install: mvn install -Dbigquery.project=dummy-project -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -Dbigquery.project=dummy-project clean verify checkstyle:checkstyle findbugs:findbugs

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    - flatmap-squad@spotify.com
